### ISSUE TITLE
Science labs not earning appropriate levels of science per day

### ISSUE THREAD

**Issue by dawnroselyn** [confusingbits/KSPInterstellar#11]
Deploy a science lab on a place like Laythe, which should generate 3.4 science per day with a smart crew.  Start research, confirm the science rate by right clicking the lab, then switch back to the space center, and fast forward 10 days.

expected result -  34 points of science earned  (approximately)
actual result -       10 points of science earned.

**Comment by confusingbits** [comment]
Is that kerbal days or earth days? The mod only calculates based on earth days.

**Comment by dawnroselyn** [comment]
"Days" as described by the datestamp in the upper left hand corner of the space center tracking station screen.

**Comment by confusingbits** [comment]
Days are either kerbin days (6 hours) or earth days (24 hours) ingame. The mod doesn't care what setting you have, a day is always 86400 seconds (24 hours).

Adding support for kerbin days is on the todo list, but it is not a high priority.

**Comment by confusingbits** [comment]
Tested in .12, it appears to be working correctly.
