### ISSUE TITLE
Reactors of all kind are "Fuel Deprived"

### ISSUE THREAD

**Issue by xATHEISTxDEITYx** [confusingbits/KSPInterstellar#12]
only the low level MX reactors put out any energy. Would it be an issue with my Resource .cfg? how would I go about fixing this issue. I can't use any higher level reactors to power ships because of this issue.

**Comment by confusingbits** [comment]
MX?

**Comment by xATHEISTxDEITYx** [comment]
Disregard, It was a conflict with the OpenResource .dll files. had two too many. thanks for being quick though.
