### ISSUE TITLE
aaa_toolbar incompatible for 0.24.2

### ISSUE THREAD

**Issue by Nomoturtle** [confusingbits/KSPInterstellar#15]
simply the response i got from the game upon startup. using mac pro 10.9.4 if it makes any difference

**Comment by confusingbits** [comment]
That's blizzy's toolbar telling you to update the toolbar. It doesn't mean that it doesn't work in either case, it is just a warning. if you click the toolbar button it should send you to the appropriate place to update.

**Comment by confusingbits** [comment]
Should be on all screens.

google blizzy toolbar and install it if it isn't' visible.

**Comment by Nomoturtle** [comment]
thanks very much, haven't tried interstellar, was disappointed to find the original incompatible with 24, you're a life saver

**Comment by confusingbits** [comment]
np , have fun. :)
