### ISSUE TITLE
Air scoops can't gather CO2

### ISSUE THREAD

**Issue by meltafire** [confusingbits/KSPInterstellar#16]
1.ISRU refinery has a reaction called "Sabatier ISRU" (LF+CO2=Methane+Ox or FractalUK KSPI wiki is out of date?). Air Inline Scoops, Air Radial Scoops (both sizes) are missing option to gather "Carbon Dioxide" or "CO2". On Kerbin a part "gas spectrometer' shows some amount of it. It's very tiny amount like H2 but we can gather Hydrogen at Kerbin.

2.Parts are missing in VAB and SPH but present in science tree. Parts are:
Parts\Utility\warpAtmIntake
1.5m Atmospheric Intake
2.5m Atmospheric Intake
Atmospheric Intakes isn't just nosecone intakes but air gatherers too.

**Comment by confusingbits** [comment]
1. resources have some changes coming, but not in .12.
2. I'll be adding intakeatm to all intakes via module manager in .12.

**Comment by confusingbits** [comment]
1. Was an error with missing ORS files. Fixed in .12
   2 I'm leaving the mod with just the radial ones for now until I get new art. Tweakscale makes them very flexible.
