### ISSUE TITLE
ORS Scanner readout

### ISSUE THREAD

**Issue by DMagic1** [confusingbits/KSPInterstellar#27]
Line 57 here c4840b9ccf57778a6e7b59720705c598315ba266, should probably be changed to say:

```
Ab = "0";
```

rather than 

```
Ab = "Broken :(";
```

It's a little more accurate that way, since a null resourceInfo value could also imply that there is simply none of that resource on the planet.

**Comment by confusingbits** [comment]
Hmm, I don't know, the message has helped me determine problems before. 0 can mean it is defined as 0 or that it is broken, since it is initialized at 0. Might better to initialed as null and handle the null for undefined cases, though I'm not sure if it makes a difference.

**Comment by DMagic1** [comment]
yeah, there is probably a better way to handle broken readouts vs. non-existent resources, that's just the simplest method
