### ISSUE TITLE
Can't Shut Down Fission Reactor in EVA

### ISSUE THREAD

**Issue by softcraft-development** [confusingbits/KSPInterstellar#28]
The [original wiki](https://github.com/FractalUK/KSPInterstellar/wiki/Reactors) states:

```
Reactors can be shut down via an EVA.
```

I saw Scott Manley do such a thing in one of his Interstellar Quest videos.

However, on the latest release, when I try to do the same, I cannot; right-clicking on the reactor during EVA brings up no menus. No option for shutting down the fission reactor exists in the non-EVA right-click menu either.

I'm on 0.24.2, OS X, and with a bevy of other mods installed.

**Comment by confusingbits** [comment]
Hmm, I had to turn a reactor back online last night, but not turn one on. I will investigate this tonight.

**Comment by confusingbits** [comment]
I had no issue shutting the reactor down with eva on my launchpad test. Please perform a clean install of .12. There is a video guide in my forum post that tells you everything you need to do to install and report problems.

**Comment by softcraft-development** [comment]
I re-tested, and found it working. My original problem that my (radiator-less during my launch) reactor had already gone into auto-shutdown mode when it overheated, and so I didn't have the option to turn it off manually. That's somewhat confusing for a newbie, but functionally correct. Thanks anyway!

**Comment by confusingbits** [comment]
I hear your feedback and I tend to agree. I'm glad that everything is working for you now.
