### ISSUE TITLE
Toggle propellant not working on Thermal Rocket Nozzle

### ISSUE THREAD

**Issue by expert7000** [confusingbits/KSPInterstellar#35]
When in the VAB, I can toggle inbetween everything, but when I launch it gets set back to Liquid and only lets me toggle between Liquid and Water.

**Comment by confusingbits** [comment]
It will only toggle between fuels that are available according to the flow rules. You may need to add some fuel lines for strangely placed tanks.

**Comment by expert7000** [comment]
Works fine now, sorry to have bothered you about something with such an easy solution.

**Comment by confusingbits** [comment]
NP. I am glad that it working for you now. :)
