### ISSUE TITLE
KSP crashed on startup

### ISSUE THREAD

**Issue by inbit** [confusingbits/KSPInterstellar#36]
After copying all the files and trying to start ksp, it crashed. 

This is the output log, hope it helps:
Initialize engine version: 4.5.2f1 (9abb1b59b47c)
GfxDevice: creating device client; threaded=1
d3d: no support for this device type (accelerated/ref)
D3D9 initialization failed
GfxDevice: creating device client; threaded=1
d3d11: failed to create D3D11 device (0x887a0004)
D3D11 initialization failed
D3D9/D3D11 initialization failed, trying OpenGL
GfxDevice: creating device client; threaded=1
OpenGL:
    Version:  OpenGL 1.1 [1.1.0]
    Renderer: GDI Generic
    Vendor:   Microsoft Corporation
    Driver:   RDPDD 6.1.7601.17514
    VRAM:     973 MB (via DXGI)
    Extensions: GL_WIN_swap_hint GL_EXT_bgra GL_EXT_paletted_texture
Crash!!!
SymInit: Symbol-SearchPath: '.;D:\games\Kerbal Space Program x64 0.24.2;D:\games\Kerbal Space Program x64 0.24.2;C:\Windows;C:\Windows\system32;SRV_C:\websymbols_http://msdl.microsoft.com/download/symbols;', symOptions: 530, UserName: 'inBit'
OS-Version: 6.1.7601 (Service Pack 1) 0x100-0x1
D:\games\Kerbal Space Program x64 0.24.2\KSP_x64.exe:KSP_x64.exe (000000013FB00000), size: 15511552 (result: 0), SymType: '-exported-', PDB: 'D:\games\Kerbal Space Program x64 0.24.2\KSP_x64.exe', fileVersion: 4.5.2.26843
C:\Windows\SYSTEM32\ntdll.dll:ntdll.dll (0000000077860000), size: 1740800 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\ntdll.dll', fileVersion: 6.1.7601.18247
C:\Windows\system32\kernel32.dll:kernel32.dll (0000000077640000), size: 1175552 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\system32\kernel32.dll', fileVersion: 6.1.7601.18015
C:\Windows\system32\KERNELBASE.dll:KERNELBASE.dll (000007FEFC890000), size: 438272 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\system32\KERNELBASE.dll', fileVersion: 6.1.7601.18015
C:\Windows\system32\HID.DLL:HID.DLL (000007FEFA440000), size: 45056 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\system32\HID.DLL', fileVersion: 6.1.7600.16385
C:\Windows\system32\msvcrt.dll:msvcrt.dll (000007FEFD5A0000), size: 651264 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\system32\msvcrt.dll', fileVersion: 7.0.7601.17744
C:\Windows\system32\WS2_32.dll:WS2_32.dll (000007FEFE9F0000), size: 315392 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\system32\WS2_32.dll', fileVersion: 6.1.7601.17514
C:\Windows\system32\RPCRT4.dll:RPCRT4.dll (000007FEFCA80000), size: 1232896 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\system32\RPCRT4.dll', fileVersion: 6.1.7601.18205
C:\Windows\system32\NSI.dll:NSI.dll (000007FEFD4F0000), size: 32768 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\system32\NSI.dll', fileVersion: 6.1.7600.16385
C:\Windows\system32\USER32.dll:USER32.dll (0000000077760000), size: 1024000 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\system32\USER32.dll', fileVersion: 6.1.7600.16385
C:\Windows\system32\GDI32.dll:GDI32.dll (000007FEFEA40000), size: 421888 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\system32\GDI32.dll', fileVersion: 6.1.7601.17514
C:\Windows\system32\LPK.dll:LPK.dll (000007FEFED00000), size: 57344 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\system32\LPK.dll', fileVersion: 6.1.7600.16385
C:\Windows\system32\USP10.dll:USP10.dll (000007FEFEAB0000), size: 823296 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\system32\USP10.dll', fileVersion: 1.626.7601.18009
C:\Windows\system32\VERSION.dll:VERSION.dll (000007FEFB790000), size: 49152 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\system32\VERSION.dll', fileVersion: 6.1.7600.16385
C:\Windows\system32\ole32.dll:ole32.dll (000007FEFE6E0000), size: 2109440 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\system32\ole32.dll', fileVersion: 6.1.7601.17514
C:\Windows\system32\SHLWAPI.dll:SHLWAPI.dll (000007FEFCE60000), size: 462848 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\system32\SHLWAPI.dll', fileVersion: 6.1.7601.17514
C:\Windows\system32\ADVAPI32.dll:ADVAPI32.dll (000007FEFD870000), size: 897024 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\system32\ADVAPI32.dll', fileVersion: 6.1.7601.18247
C:\Windows\SYSTEM32\sechost.dll:sechost.dll (000007FEFD850000), size: 126976 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\sechost.dll', fileVersion: 6.1.7600.16385
C:\Windows\system32\SHELL32.dll:SHELL32.dll (000007FEFD950000), size: 14188544 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\system32\SHELL32.dll', fileVersion: 6.1.7601.18103
C:\Windows\system32\OPENGL32.dll:OPENGL32.dll (000007FEF9020000), size: 1167360 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\system32\OPENGL32.dll', fileVersion: 6.1.7600.16385
C:\Windows\system32\GLU32.dll:GLU32.dll (000007FEF9230000), size: 184320 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\system32\GLU32.dll', fileVersion: 6.1.7600.16385
C:\Windows\system32\DDRAW.dll:DDRAW.dll (000007FEF8D20000), size: 987136 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\system32\DDRAW.dll', fileVersion: 6.1.7600.16385
C:\Windows\system32\DCIMAN32.dll:DCIMAN32.dll (000007FEF9220000), size: 32768 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\system32\DCIMAN32.dll', fileVersion: 6.1.7600.16385
C:\Windows\system32\SETUPAPI.dll:SETUPAPI.dll (000007FEFD670000), size: 1929216 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\system32\SETUPAPI.dll', fileVersion: 6.1.7601.17514
C:\Windows\system32\CFGMGR32.dll:CFGMGR32.dll (000007FEFC700000), size: 221184 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\system32\CFGMGR32.dll', fileVersion: 6.1.7601.17514
C:\Windows\system32\OLEAUT32.dll:OLEAUT32.dll (000007FEFD410000), size: 880640 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\system32\OLEAUT32.dll', fileVersion: 6.1.7601.17676
C:\Windows\system32\DEVOBJ.dll:DEVOBJ.dll (000007FEFC790000), size: 106496 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\system32\DEVOBJ.dll', fileVersion: 6.1.7600.16385
C:\Windows\system32\dwmapi.dll:dwmapi.dll (000007FEF9A50000), size: 98304 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\system32\dwmapi.dll', fileVersion: 6.1.7600.16385
C:\Windows\system32\WINMM.dll:WINMM.dll (000007FEFA400000), size: 241664 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\system32\WINMM.dll', fileVersion: 6.1.7600.16385
C:\Windows\system32\MSACM32.dll:MSACM32.dll (000007FEF9740000), size: 98304 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\system32\MSACM32.dll', fileVersion: 6.1.7600.16385
C:\Windows\system32\IMM32.dll:IMM32.dll (000007FEFD640000), size: 188416 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\system32\IMM32.dll', fileVersion: 6.1.7600.16385
C:\Windows\system32\MSCTF.dll:MSCTF.dll (000007FEFD1A0000), size: 1085440 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\system32\MSCTF.dll', fileVersion: 6.1.7600.16385
C:\Windows\system32\DNSAPI.dll:DNSAPI.dll (000007FEFBD40000), size: 372736 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\system32\DNSAPI.dll', fileVersion: 6.1.7601.17570
C:\Windows\system32\IPHLPAPI.DLL:IPHLPAPI.DLL (000007FEFA3A0000), size: 159744 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\system32\IPHLPAPI.DLL', fileVersion: 6.1.7601.17514
C:\Windows\system32\WINNSI.DLL:WINNSI.DLL (000007FEFA390000), size: 45056 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\system32\WINNSI.DLL', fileVersion: 6.1.7600.16385
C:\Windows\system32\WINHTTP.dll:WINHTTP.dll (000007FEFA0A0000), size: 462848 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\system32\WINHTTP.dll', fileVersion: 6.1.7601.17514
C:\Windows\system32\webio.dll:webio.dll (000007FEFA030000), size: 409600 (result: 0), SymType: '-nosymbols-', PDB: 'C:\Windows\system32\webio.dll', fileVersion: 6.1.7601.17725
D:\games\Kerbal Space Program x64 0.24.2\KSP_x64_Data\Mono\mono.dll:mono.dll (000007FEF8A40000), size: 2985984 (result: 0), SymType: '-exported-', PDB: 'D:\games\Kerbal Space Program x64 0.24.2\KSP_x64_Data\Mono\mono.dll'
C:\Windows\system32\PSAPI.DLL:PSAPI.DLL (0000000077A20000), size: 28672 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\system32\PSAPI.DLL', fileVersion: 6.1.7600.16385
C:\Windows\system32\MSWSOCK.dll:MSWSOCK.dll (000007FEFBEC0000), size: 348160 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\system32\MSWSOCK.dll', fileVersion: 6.1.7601.18254
C:\Windows\system32\uxtheme.dll:uxtheme.dll (000007FEFA800000), size: 352256 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\system32\uxtheme.dll', fileVersion: 6.1.7600.16385
C:\Windows\system32\CRYPTBASE.dll:CRYPTBASE.dll (000007FEFC580000), size: 61440 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\system32\CRYPTBASE.dll', fileVersion: 6.1.7600.16385
C:\Windows\system32\DXGIDebug.dll:DXGIDebug.dll (000007FEF49C0000), size: 126976 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\system32\DXGIDebug.dll', fileVersion: 9.30.960.9200
C:\Windows\system32\WINTRUST.dll:WINTRUST.dll (000007FEFC740000), size: 237568 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\system32\WINTRUST.dll', fileVersion: 6.1.7601.18205
C:\Windows\system32\CRYPT32.dll:CRYPT32.dll (000007FEFC900000), size: 1490944 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\system32\CRYPT32.dll', fileVersion: 6.1.7601.18205
C:\Windows\system32\MSASN1.dll:MSASN1.dll (000007FEFC6F0000), size: 61440 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\system32\MSASN1.dll', fileVersion: 6.1.7601.17514
C:\Windows\system32\nvoglv64.DLL:nvoglv64.DLL (0000000054920000), size: 31703040 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\system32\nvoglv64.DLL', fileVersion: 9.18.13.3523
C:\Windows\system32\ntmarta.dll:ntmarta.dll (000007FEFB200000), size: 184320 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\system32\ntmarta.dll', fileVersion: 6.1.7600.16385
C:\Windows\system32\WLDAP32.dll:WLDAP32.dll (000007FEFE990000), size: 335872 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\system32\WLDAP32.dll', fileVersion: 6.1.7601.17514
C:\Windows\system32\dbghelp.dll:dbghelp.dll (000007FEEE2F0000), size: 1200128 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\system32\dbghelp.dll', fileVersion: 6.1.7601.17514
C:\Windows\system32\SspiCli.dll:SspiCli.dll (000007FEFC4F0000), size: 151552 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\system32\SspiCli.dll', fileVersion: 6.1.7601.17725

========== OUTPUTING STACK TRACE ==================

(0x000000013FFB7661) (KSP_x64): (filename not available): Behaviour::Transfer<RemapPPtrTransfer> + 0x29791
(0x0000000000010000) ((module-name not available)): (filename not available): (function-name not available) + 0x0

========== END OF STACKTRACE ===========

***\* Crash! ****

**Comment by confusingbits** [comment]
64 bit crashes randomly. It's a problem with ksp, not interstellar.
