### ISSUE TITLE
Generators type still shows in the VAB when no alternative type is available.

### ISSUE THREAD

**Issue by ghost** [confusingbits/KSPInterstellar#47]
The parts stay unupgraded when playing in sandbox. The generator is still a Brayton Cycle Gas Turbine and there is no option to upgrade/downgrade.

**Comment by confusingbits** [comment]
There are no upgrades for reactors, radiators or generators. Please see the thread OP for more information about the changes in kspil.

**Comment by Joeppie** [comment]
Perhaps showing generator type in construction buildings is no longer useful?

**Comment by confusingbits** [comment]
Yes, the correct behavior would be to not show type if there is no option to configure it.
