### ISSUE TITLE
Ship backward compatibility.

### ISSUE THREAD

**Issue by Poofey** [confusingbits/KSPInterstellar#55]
Upgraded directly from Experimental version, have backup of savefile so i can just go back but half my ships get unloaded due to not having the actual parts, i tried updating the tech tree and re-purchasing the parts in the R&D department then copy/pasting the Flighstate from backup file to the persistent file but the ships get unloaded again, i noticed the reactors are no longer in different sizes, as well as the generators/engines, among other parts that the loading error pulls out

question is, is there a way to edit the savefile to bring back those ships. one of them is a station that took quite a while to assemble...

**Comment by confusingbits** [comment]
Not really. Which is why I put the warning about save breaking in the forum OP.

**Comment by Poofey** [comment]
yeah i found out about the new thread well after i posted this, i'll just have to redesign and resend those 2 stations plus a couple other vessels. cheers.
