### ISSUE TITLE
Infinitely Expanding Parts

### ISSUE THREAD

**Issue by gajbooks** [confusingbits/KSPInterstellar#56]
This might be user error or the glitch of some other mod's plugin, but the reactors and thermal power receivers keep expanding infinitely on mouseover in the VAB/SPH. Am I missing some plugin something else overwrote or is this truly a bug? I understand there is a fixer for the graphical bug, but apparently it means a module isn't working? This only affects parts from this mod. All other mods seem to work fine with this setup.

**Comment by confusingbits** [comment]
Please see the kspil forum thread, there is video to explain how to do a proper install.
