### ISSUE TITLE
radiation kills -> shielding.

### ISSUE THREAD

**Issue by AlonzoTG** [confusingbits/KSPInterstellar#59]
Hey, it needs to be possible to shield pods/labs/???plugins from radiation I had my vista pointed AWAY from my main vessel at a range of 500m and it still killed a kerbal!!! That's not cool. =(  If I am going to go warp speed after the last unlock here, I'm going to need these vista engines to put me in the right intertial frame. =\ 

What's your thinking on this anyway H2 + H3 -> He4 + n ? even still, the flow rates are just not enough to irradiate a sphere an entire KM in diameter at lethal levels, in open space, I don't think. =\ 

My previous stock-like nuclear designs were up at around 1,800-2,000 tons and were too fragile to be usable. There needs to be a setting somewhere to nerf radiation anyway, it's junt not adding much to the game.

**Comment by confusingbits** [comment]
Given the power or the vista engine, some significant drawbacks are reasonable.
