### ISSUE TITLE
[Exception]: MissingMethodException: Method not found: 'Part.GetConnectedResources'.

### ISSUE THREAD

**Issue by EoD** [confusingbits/KSPInterstellar#6]
It took me a while to figure out what was going one, but if I jump to an old ship (from 0.23.5 interstellar 0.11) my debug log spams the messages:

[Exception]: MissingMethodException: Method not found: 'Part.GetConnectedResources'.
[Exception]: MissingMethodException: Method not found: 'Part.GetConnectedResources'.
[Exception]: MissingMethodException: Method not found: 'Part.GetConnectedResources'.
[Exception]: MissingMethodException: Method not found: 'Part.GetConnectedResources'.

**Comment by EoD** [comment]
Argh, nevermind. Apparently I had the following files

./OpenResourceSystem/Plugins/OpenResourceSystem.dll
./OpenResourceSystem/Plugins/OpenResourceSystem_1_1_0.dll

Could you maybe deliver one dll (so the update overwrites the other one) in your release? Or is there a reason to keep both?

**Comment by confusingbits** [comment]
OpenResourceSystem.dll is from MKS.
OpenResourceSystem/Plugins/OpenResourceSystem_1_1_0.dll is from KSPI, but incompatible with the current version of the game due to an api change from squad.
The official version of KSPI is incompatible with the the current version of the game.

**Comment by confusingbits** [comment]
Oops, I just realize this was a comment to the experimental version.

Use the version that comes with KSPI experimental. It has the appropriate bug fix. Delete the MKS version.

**Comment by EoD** [comment]
Yeah, I already deleted it and I am using the ORSv1_1 from your tree. I wouldn't post an issue in your fork if it were from the official release ;-)
