### ISSUE TITLE
Uh Oh

### ISSUE THREAD

**Issue by hunterleavitt-dev** [confusingbits/KSPInterstellar#60]
When i get into the VAB I click on a part and it's solid, but when I click on another it will connect to the first part, but won't be solid. Then, when I click launch, it crashes. I am currently using KSP 0.24.2 with the following mods: KW Rocketry, Holligan Labs airships, B9 Aerospace, Spaceplane Plus, Lazor System, KAX, Firespitter, Near Future Propulsion, Mechjeb 2, and Lazor Guided Weapons (Including Toshs' Sunbeam). Please help me and fix this. Thanks.

**Comment by confusingbits** [comment]
You have improper install, please see the video in the kspil forum OP.

**Comment by hunterleavitt-dev** [comment]
K. Thanks.
