### ISSUE TITLE
Antimatter containers should be empty in VAB

### ISSUE THREAD

**Issue by Ddall** [confusingbits/KSPInterstellar#61]
The antimatter containers come fully fueled in the VAB. 
It was way more challenging when the only way to get antimatter was to have traps in orbit (or use the lab). Now you have an unlimited supply of fuel for your alcubierre drive.

Also, it looks like the containers don't require constant power in order to -not explode- like they used to.

**Comment by confusingbits** [comment]
Some of the resource mechanics are not fully implemented, like the resource costs are merely placeholder for now.

Some of that will be hold until I can reconverge with fractaluk's updates, but I will have to wait until he has a finished version to do that.
