### ISSUE TITLE
Antimatter collector rate displays incorrectly

### ISSUE THREAD

**Issue by omion** [confusingbits/KSPInterstellar#62]
When adjusting antimatter collector part sizes, the displayed collection rate may show up wrong for non-2.5m parts.

This seems to happen because collectionMultiplier is multiplied twice for the collectionRate string:
In AntimatterCollector.cs @ OnFixedUpdate():
collection_rate_d = flux \* collectionMultiplier \* 86400;

in AntimatterCollector.cs @ OnUpdate():
collectionRate = (collection_rate_d \* collectionMultiplier).ToString("0.00") + " mg/day";

Essentially, collectionRate is displayed as:
flux \* collectionMultiplier \* collectionMultiplier \* 86400.

I haven't tried it, but I'm pretty sure the solution would be to remove the collectionMultiplier from the collectionRate assignment.

**Comment by Bishop149** [comment]
Was going to leave the same issue, 5m, 3.5m and 2.5m collectors all display the same collection rate at any given point. Haven't tested enough to see if the rates are different in reality!
