### ISSUE TITLE
MTER-S Microwave Thermal Receiver useless

### ISSUE THREAD

**Issue by ichaleynbin** [confusingbits/KSPInterstellar#8]
So, I'm attempting to get a spaceplane into orbit and powered via a plasma thruster and MTER-S combination, but the MTER is all but useless. I have a nice relay network, and more than enough power (the MTER shows between 4 and 14 GW received while taking off) but the reception is very, very spotty. It'll on occasion simply drop all power input, while not showing a change in input power, resulting in both thermal power and megajoules dropping to zero, causing my engine to fail. 

This receiver is so bad that I don't depend on it to get off the ground, instead I have 2 thermal turbojets to get myself up to about 15km, where I turn on the plasma thruster, which gets me to space no problem. But when I get to space, I have no power available to run the thruster, despite showing between 1 and 2 GW on the receiver. It simply has no megajoules available, so it shuts the engine down. When in the atmosphere, it's got plenty of power, but as soon as I get up to 70-110km, it has nothing available. 

I realize this is probably because of how the MTER receives power, radially and not axially. My relays are at either end of the craft, and not on the side of it, and rotating it does not help. But I can't change my orientation in space, I have to fire the node the way I have to fire it, and that's that. 

Which makes this part all but useless. It's an inline, axial orientation will never change. Timing the takeoff such that the relays are in a good position for circularization burn at apoapsis actually makes it worse. I'm pretty clearly aligned radially with both a relay and a power generator, but while I'm receiving 34 gigawatts, I'm getting no megajoules. After burn was initiated (I actually got about 20 dV out of the burn before I ran out of megajoules) input power stabilized at 5004 MW, and I've got no megajoules incoming. 

This MTER is completely useless, for this particular design at the least, and it seems like it would be useless for anything, as I've got input power but no megajoules produced. I'd like to think this isn't on me, but if you've got questions as to the circumstances this happened in, I'd be happy to answer them. In the meanwhile, I'm seriously considering dropping KSPInterstellar, because I'm getting nothing out of it but headaches. There are some truly epic ideas here, but they don't actually function.

**Comment by confusingbits** [comment]
The MTER is a thermal receiver, as the name suggests. It converts MJ received into thermal power. It does not make MJ available to the vessel. The only engines that use thermal power are the thermal nozzles and thermal turbojets. If you wish to use an electric engine, use one of the dishes or place generator on the thermal receiver.
